name: Auto Tailscale OpenVPN

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"  # runs every 6 hours to re-init the VPN automatically

jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:

      # 1️⃣ Update system and install dependencies
      - name: Update & Install Packages
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install openvpn easy-rsa iproute2 curl jq -y

      # 2️⃣ Install Tailscale
      - name: Install Tailscale
        run: curl -fsSL https://tailscale.com/install.sh | sh

      # 3️⃣ Connect Tailscale with auth key
      - name: Connect Tailscale
        env:
          TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
        run: |
          sudo tailscale up --authkey $TS_AUTH_KEY --hostname github-runner --accept-routes

      # 4️⃣ Setup OpenVPN PKI
      - name: Setup OpenVPN PKI
        run: |
          mkdir -p ~/openvpn-ca
          cd ~/openvpn-ca
          if [ ! -d pki ]; then
            ./easyrsa init-pki
            echo | ./easyrsa build-ca nopass
            ./easyrsa gen-req server nopass
            ./easyrsa sign-req server server
            ./easyrsa gen-dh
            openvpn --genkey --secret ta.key
            ./easyrsa gen-req client1 nopass
            ./easyrsa sign-req client client1
          fi

      # 5️⃣ Configure OpenVPN server
      - name: Configure OpenVPN
        run: |
          sudo bash -c 'cat > /etc/openvpn/server.conf <<EOF
          port 1194
          proto udp
          dev tun
          ca ~/openvpn-ca/pki/ca.crt
          cert ~/openvpn-ca/pki/issued/server.crt
          key ~/openvpn-ca/pki/private/server.key
          dh ~/openvpn-ca/pki/dh.pem
          server 10.8.0.0 255.255.255.0
          ifconfig-pool-persist ipp.txt
          keepalive 10 120
          cipher AES-256-CBC
          persist-key
          persist-tun
          status openvpn-status.log
          verb 3
          tls-auth ~/openvpn-ca/ta.key 0
          EOF'

      # 6️⃣ Start OpenVPN in background with retry
      - name: Start OpenVPN
        run: |
          sudo pkill openvpn || true
          nohup sudo openvpn --config /etc/openvpn/server.conf & sleep 5

      # 7️⃣ Generate client config dynamically using Tailscale IP
      - name: Generate client.ovpn
        run: |
          HOST=$(tailscale ip -4)
          PORT=1194
          mkdir -p ~/client-config
          cat <<EOF > ~/client-config/client.ovpn
          client
          dev tun
          proto udp
          remote $HOST $PORT
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          verb 3
          <ca>
          $(cat ~/openvpn-ca/pki/ca.crt)
          </ca>
          <cert>
          $(cat ~/openvpn-ca/pki/issued/client1.crt)
          </cert>
          <key>
          $(cat ~/openvpn-ca/pki/private/client1.key)
          </key>
          EOF

      # 8️⃣ Upload client.ovpn as artifact for download
      - name: Upload client.ovpn
        uses: actions/upload-artifact@v4
        with:
          name: client-ovpn
          path: ~/client-config/client.ovpn
          if-no-files-found: warn
