name: FreeVPS-OpenVPN-Tailscale

on:
  workflow_dispatch:   # allows manual start
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours automatically

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENVPN_PORT: 1194
      TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
    steps:
      - name: Update & Install Dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y openvpn easy-rsa jq curl ufw

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale
        run: |
          sudo tailscale up --authkey $TS_AUTH_KEY --hostname github-runner --accept-routes

      - name: Setup Easy-RSA
        run: |
          make-cadir ~/openvpn-ca
          cd ~/openvpn-ca
          ./easyrsa init-pki
          echo -e "\n" | ./easyrsa build-ca nopass
          ./easyrsa gen-req server nopass
          ./easyrsa sign-req server server
          ./easyrsa gen-dh
          openvpn --genkey --secret ta.key
          ./easyrsa gen-req client1 nopass
          ./easyrsa sign-req client client1

      - name: Create OpenVPN Server Config
        run: |
          sudo bash -c 'cat > /etc/openvpn/server.conf <<EOF
          port $OPENVPN_PORT
          proto tcp
          dev tun
          ca /home/runner/openvpn-ca/pki/ca.crt
          cert /home/runner/openvpn-ca/pki/issued/server.crt
          key /home/runner/openvpn-ca/pki/private/server.key
          dh /home/runner/openvpn-ca/pki/dh.pem
          server 10.8.0.0 255.255.255.0
          ifconfig-pool-persist ipp.txt
          keepalive 10 120
          cipher AES-256-CBC
          persist-key
          persist-tun
          status openvpn-status.log
          verb 3
          EOF'

      - name: Start OpenVPN Server
        run: |
          sudo openvpn --config /etc/openvpn/server.conf --daemon
          sleep 5

      - name: Generate Client Config
        run: |
          cat <<EOF > client.ovpn
          client
          dev tun
          proto tcp
          remote $(tailscale ip -4) $OPENVPN_PORT
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          verb 3
          <ca>
          $(cat ~/openvpn-ca/pki/ca.crt)
          </ca>
          <cert>
          $(cat ~/openvpn-ca/pki/issued/client1.crt)
          </cert>
          <key>
          $(cat ~/openvpn-ca/pki/private/client1.key)
          </key>
          EOF

      - name: Upload Client Config
        uses: actions/upload-artifact@v4
        with:
          name: client-ovpn
          path: client.ovpn
