name: OpenVPN + Tailscale Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  openvpn-tailscale:
    runs-on: ubuntu-latest
    env:
      TS_AUTH_KEY: ${{ secrets.TS_AUTH_KEY }}
      OPENVPN_PORT: 1194

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn easy-rsa curl jq ufw openssh-client openssh-server

      - name: Install Tailscale
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect Tailscale
        run: |
          sudo tailscale up --authkey $TS_AUTH_KEY --hostname github-runner --accept-routes

      - name: Set up Easy-RSA for OpenVPN
        run: |
          mkdir -p ~/openvpn-ca
          cd ~/openvpn-ca
          make-cadir .
          cd ~/openvpn-ca
          # Set batch mode and predefine CN
          export EASYRSA_BATCH=1
          export EASYRSA_REQ_CN="github-runner"
          # Initialize PKI and build CA
          ./easyrsa init-pki
          ./easyrsa build-ca nopass
          # Generate server certificate
          ./easyrsa gen-req server nopass
          ./easyrsa sign-req server server
          # Generate client certificate
          ./easyrsa gen-req client1 nopass
          ./easyrsa sign-req client client1
          ./easyrsa gen-dh

      - name: Generate OpenVPN server config
        run: |
          cat <<EOF | sudo tee /etc/openvpn/server.conf
          port $OPENVPN_PORT
          proto tcp
          dev tun
          ca ~/openvpn-ca/pki/ca.crt
          cert ~/openvpn-ca/pki/issued/server.crt
          key ~/openvpn-ca/pki/private/server.key
          dh ~/openvpn-ca/pki/dh.pem
          server 10.8.0.0 255.255.255.0
          keepalive 10 120
          persist-key
          persist-tun
          cipher AES-256-CBC
          user nobody
          group nogroup
          status /var/log/openvpn-status.log
          verb 3
          EOF

      - name: Start OpenVPN server
        run: |
          sudo systemctl enable openvpn@server
          sudo systemctl start openvpn@server

      - name: Generate client config
        run: |
          cat <<EOF > client.ovpn
          client
          dev tun
          proto tcp
          remote <your-server-ip-or-tailscale-ip> $OPENVPN_PORT
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          verb 3
          <ca>
          $(cat ~/openvpn-ca/pki/ca.crt)
          </ca>
          <cert>
          $(cat ~/openvpn-ca/pki/issued/client1.crt)
          </cert>
          <key>
          $(cat ~/openvpn-ca/pki/private/client1.key)
          </key>
          EOF

      - name: Upload client config as artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-ovpn
          path: client.ovpn
