name: FreeVPS-OpenVPN-Tailscale

on:
  workflow_dispatch:   # manual trigger
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TS_CLIENT_ID: ${{ secrets.TS_CLIENT_ID }}
      TS_CLIENT_SECRET: ${{ secrets.TS_CLIENT_SECRET }}
      OPENVPN_PORT: 1194

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y openvpn easy-rsa jq curl unzip

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale
        run: |
          sudo tailscale up \
            --oauth-client-id $TS_CLIENT_ID \
            --oauth-client-secret $TS_CLIENT_SECRET \
            --hostname github-runner \
            --accept-routes

      - name: Setup Easy-RSA and generate CA
        run: |
          make-cadir ~/openvpn-ca
          cd ~/openvpn-ca
          ./easyrsa init-pki
          echo -en "\n" | ./easyrsa build-ca nopass
          ./easyrsa gen-req server nopass
          ./easyrsa sign-req server server
          ./easyrsa gen-req client1 nopass
          ./easyrsa sign-req client client1
          ./easyrsa gen-dh

      - name: Configure OpenVPN server
        run: |
          sudo cp ~/openvpn-ca/pki/ca.crt /etc/openvpn/
          sudo cp ~/openvpn-ca/pki/issued/server.crt /etc/openvpn/
          sudo cp ~/openvpn-ca/pki/private/server.key /etc/openvpn/
          sudo cp ~/openvpn-ca/pki/dh.pem /etc/openvpn/dh2048.pem

          cat <<EOF | sudo tee /etc/openvpn/server.conf
          port $OPENVPN_PORT
          proto tcp
          dev tun
          ca /etc/openvpn/ca.crt
          cert /etc/openvpn/server.crt
          key /etc/openvpn/server.key
          dh /etc/openvpn/dh2048.pem
          server 10.8.0.0 255.255.255.0
          keepalive 10 120
          persist-key
          persist-tun
          status /var/log/openvpn-status.log
          verb 3
          EOF

      - name: Start OpenVPN server
        run: sudo openvpn --config /etc/openvpn/server.conf --daemon

      - name: Generate client.ovpn
        run: |
          TAILSCALE_IP=$(tailscale ip -4)
          cat <<EOF > client.ovpn
          client
          dev tun
          proto tcp
          remote $TAILSCALE_IP $OPENVPN_PORT
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          remote-cert-tls server
          cipher AES-256-CBC
          verb 3
          <ca>
          $(cat ~/openvpn-ca/pki/ca.crt)
          </ca>
          <cert>
          $(cat ~/openvpn-ca/pki/issued/client1.crt)
          </cert>
          <key>
          $(cat ~/openvpn-ca/pki/private/client1.key)
          </key>
          EOF

      - name: Upload OpenVPN client config
        uses: actions/upload-artifact@v4
        with:
          name: client-ovpn
          path: client.ovpn
